### ISSUE TITLE
BankAccount created on front-end but later does not exist

### ISSUE THREAD

**Issue by TimKJones** [balanced/balanced-ruby#200] opened 2014-11-08 19:11 UTC
A user added a bank account, whose id was posted to the back-end to be associated with that user's Customer resource. When that id was fetched server-side, it did not exist. This has happened a couple times, but I can't figure out the exact circumstances that cause it to happen. I would assume that the BankAccount resource was created successfully if an id was returned, but that doesn't seem to be the case.

Has anyone else experienced this?

**Comment by remear** [comment] 2014-11-09 00:49
- How long generally elapses between the user-side tokenization of the funding instrument and the time you attempt to fetch it?
- What version of balanced-ruby are you using?

We'd gladly look deeper into this if you could provide that reproducible example, funding instrument hrefs, and OHMs of these tokenizations and server-side authenticated requests to fetch the funding instrument.

**Comment by TimKJones** [comment] 2014-11-11 00:47
Thanks for looking into this!
- After the funding instrument is tokenized, it is immediately POSTed to our server, where it is placed on a redis queue for sidekiq to pick it up and fetch it. This process should take a few hundred milliseconds.
- We're using balanced-ruby version 1.1.1

I can give you the funding instrument href - what is the best way to deliver that to you? 

I'm not sure how to find the OHMs of the tokenizations. It doesn't look like it shows up in our logs, and I don't have it saved anywhere. I understand that may make it difficult. I was hoping that you may be able to find something by looking into that funding instrument href that was returned.

**Comment by mjallday** [comment] 2014-11-12 01:34
@TimKJones what's the marketplace ID and the time that this occurred? as @remear pointed out in the future the ultimate way for us to debug it is to get the `X-Balanced-Guru-ID` header from the HTTP response as we can look that up easily. 

Our system persists card tokens immediately so there shouldn't be any latency but we're happy to take a look and see what we can see.

**Comment by TimKJones** [comment] 2014-11-21 16:07
Thanks @mjallday. I'm not sure how to extract the `X-Balanced-Guru-ID` header, but I can give you the marketplace ID, the approximate time it occurred, and the funding instrument href. Should I deliver these to you via email?

**Comment by mjallday** [comment] 2014-11-22 00:12
@TimKJones the funding instrument href and time of creation is all we need. since it will have expired you can paste it right here in github or send it to support@balancedpayments.com if you prefer and reference this issue in the message. we'll get someone to look. 

is this still continuing to occur for you?

**Comment by remear** [comment] 2015-01-05 17:48
Closing. Will re-open if this is still occurring and more information is supplied.

**Closed as completed by remear** 2015-01-05 17:48 UTC
